name: Continuous Integration

on:
  push:
    branches: [ "main" ]

jobs:
  Validacao-Inicial-HTML: # Nome descritivo (Exercício 4)
    runs-on: ubuntu-latest # O coração do Dia 5
    
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Verificar versão do SO
        run: lsb_release -a # Comando Linux para ver detalhes do Runner