name: Continuous Integration

# 1. Definindo os GATILHOS (Triggers)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# 2. Definindo o que deve ser feito (Jobs)
jobs:
  validacao-estatica:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      # Em vez de Node, vamos apenas validar se os arquivos essenciais existem
      - name: Verificar arquivos do site
        run: |
          ls -la
          test -f index.html && echo "HTML encontrado!"
          test -f style.css && echo "CSS encontrado!"

      - name: Mensagem de Sucesso
        run: echo "O Workflow de infraestrutura rodou com sucesso!"