name: Deploy to GitHub Pages

# Gatilhos: Quando o rob√¥ deve trabalhar
on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

# Permiss√µes: O "crach√°" de acesso do rob√¥
permissions:
  contents: read
  pages: write
  id-token: write

# Concorr√™ncia: Organiza a fila de deploys
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # O Servidor (Runner): Onde a m√°gica acontece
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixa o seu c√≥digo para o servidor
      - name: Checkout
        uses: actions/checkout@v4

      # üöÄ Passo 2 (Foco Dia 05): Interagindo com o sistema operacional do Runner
      - name: Verificar vers√£o do SO (Explorando o Linux)
        run: lsb_release -a

      # Passo 3: Configura o ambiente para o GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      # Passo 4: Empacota o site (HTML/CSS) para o servidor
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Define que o site est√° na raiz do projeto
          
      # Passo 5: Publica o site oficialmente
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4